### ISSUE TITLE
Dedicated Server shuts down after a few moments.

### ISSUE THREAD

**Issue by lyzio** [lyzio/Fort-DwarfCraft#1]
Version: 0.1
Server: Ubuntu
Client: Windows 10

Starting server, without problem.
Server can run, without any problem, backup and such.

When a player joins, no items can be picked up. Blocks can break but do not become items. It is possible to walk around.
After a few moments ~1 min. The server crashes.

[crash-2021-05-09_10.51.09-server.txt](https://github.com/lyzio/Fort-DwarfCraft/files/6447577/crash-2021-05-09_10.51.09-server.txt)

**Comment by lyzio** [comment]
Is caused by unlocking all achivements at begining of player joining.
Mods that uses this is Charm and Quark.

**Comment by lyzio** [comment]
Needs further investigation. Even with this change it crashes.

Seems to be Charm that still unlocks even though Quark is present.

`	at svenhjol.charm.module.AutomaticRecipeUnlock.unlockRecipes(AutomaticRecipeUnlock.java:39) ~[charm:2.3.2] {re:classloading}
	at svenhjol.charm.module.AutomaticRecipeUnlock.onPlayerLoggedIn(AutomaticRecipeUnlock.java:29) ~[charm:2.3.2] {re:classloading}`

**Comment by lyzio** [comment]
Is now working, though the automatic getting of all recpies is not. Though the game seems not to be crashing (at start) anymore with both Charm and Quark active.

Implemented a fix that disables watchdog and gives lag instead.
